### ISSUE TITLE
Problem with 'https://github.com/vitusbenson/torch_advection.git'

### ISSUE THREAD

**Issue by rijul01** [vitusbenson/neural_transport#9]
I am attempting to install all the required packages, but I'm encountering an issue with the command pip3 install git+https://github.com/vitusbenson/torch_advection.git. It prompts me to enter a GitHub password.

**Comment by vitusbenson** [comment]
Hey! Thanks for checking out our package! This is a mistake on my side, the torch_advection package is no longer necessary, you can just drop that requirement. I will update the readme when I am back in office.
Cheers
Vitus

**Comment by vitusbenson** [comment]
#11  should fix this. Closing for now.
